# Generated by Django 6.0 on 2026-02-17 16:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_projectpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('PREFERENCE_SUBMITTED', 'Preference Submitted'), ('PREFERENCE_SELECTED', 'Preference Selected'), ('PREFERENCE_REJECTED', 'Preference Rejected'), ('PROPOSAL_ACCEPTED', 'Proposal Accepted'), ('PROPOSAL_REJECTED', 'Proposal Rejected'), ('ASSIGNMENT_CREATED', 'Assignment Created')], max_length=50)),
                ('related_id', models.CharField(blank=True, max_length=50, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
