# Generated by Django 6.0 on 2026-03-04 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='submission_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
