# Generated by Django 6.0 on 2026-03-08 11:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_assignment_submission_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('research_quality', models.IntegerField()),
                ('implementation_quality', models.IntegerField()),
                ('report_quality', models.IntegerField()),
                ('presentation', models.IntegerField()),
                ('comments', models.TextField(blank=True)),
                ('total_marks', models.IntegerField()),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='marking', to='core.assignment')),
                ('marked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
