# Generated by Django 6.0 on 2026-03-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_marking'),
    ]

    operations = [
        migrations.AddField(
            model_name='marking',
            name='is_released',
            field=models.BooleanField(default=False),
        ),
    ]
